language: elixir
matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.2
      elixir: 1.10
    - otp_release: 26.2
      elixir: 1.18
      env: STRICT=true

env:
  global:
    - MIX_HOME=$(pwd)/.mix
script:
  - if [ "${STRICT}" = "true" ]; then mix compile --warnings-as-errors; fi
  - mix test
  - mix dialyze
  - if [ "${STRICT}" = "true" ]; then mix format --check-formatted; fi
cache:
  directories:
  - .mix
  - _build
